### ISSUE TITLE
Add real unit tests for dataMap function

### ISSUE THREAD

**Issue by fbuchinger** [ForestMist/logitech-g27#5]
Hi Daniel,

first of all thanks a lot for providing this fantastic and comprehensive library for the Logitech G27 steering wheel! I'm especially impressed by its forceFeedback support. You might have noticed [my fork](https://github.com/fbuchinger/logitech-g25), that tries to port your library to the G25 wheel.

One minor nitpick: Have you thought about adding "real" unit tests for the dataMap function, that compare the read buffers against the expected wheel status? This would make the job for contributors much easier, because they cannot run into regressions any more. You might take a look at my [mocha tests for the G25](https://github.com/fbuchinger/logitech-g25/blob/master/test/test.js).

**Comment by fbuchinger** [comment]
Thanks for the thourough feedback! Currently my G25 fork supports steering,
gear shifting and Pedal control. Force feedback etc is still missing.

Daniel Gagan <notifications@github.com> schrieb am So., 22. Apr. 2018,
17:22:

**Comment by ForestMist** [comment]
You are very welcome and congrats on your excellent progress. ^_^

Marking this issue as resolved since nothing is changing right now in this library. Thanks for the ideas / discussion though.
