### ISSUE TITLE
Anyway to trigger wheel calibration or modify wheel center ?

### ISSUE THREAD

**Issue by FreshPr** [ForestMist/logitech-g27#6]
When you first plug in the wheel it runs a calibration. 

Is there a command to trigger the calibration process or adjust the center point left/right manually without unplugging /replugging the wheel. 

I will check out the data exchanged via usb analyzer, but am wondering if you already came across some information while developing this.

**Comment by ForestMist** [comment]
Hi there. ^_^

Not sure if you can adjust the center point.

You should be able to re-run the calibration process by taking a copy of the init code from inside https://github.com/ForestMist/logitech-g27/blob/master/code/index.js

So maybe something like this...

```js
var g = require('logitech-g27')

g.connect(function(err) {
    // do something here or wait awhile

    // calibrate again
    // G27 Racing Wheel init from https://www.lfs.net/forum/post/1587144#post1587144
    g.relayOS([0xf8, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00])
    g.relayOS([0xf8, 0x09, 0x04, 0x01, 0x00, 0x00, 0x00])
})
```

I don't have my wheel hooked up to my computer right now so the above code may need tweaking.
